AWSTemplateFormatVersion: 2010-09-09
Description: Cognito Stack

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment of this stack of resources

Mappings:
  DomainName:
    dev:
      name: user-pool-service-dev
    staging:
      name: user-pool-service-staging
    prod:
      name: user-pool-service-prod

Resources:
  #Creates an Amazon Cognito user pool
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !FindInMap [DomainName, !Ref Environment, name]
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: true
  #Specifies an Amazon Cognito user pool client
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: user-pool-client
      GenerateSecret: false
      UserPoolId: !Ref UserPool
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      CallbackURLs:
        - http://localhost:3000/authenticated
      DefaultRedirectURI: http://localhost:3000/authenticated
      LogoutURLs:
        - http://localhost:3000/signedout
      SupportedIdentityProviders:
        - COGNITO
  #Creates a new domain for a user pool
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !FindInMap [DomainName, !Ref Environment, name]
      UserPoolId: !Ref UserPool
Outputs:
  UserPoolId:
    Description: "UserPoolId"
    Value: "UserPool::Id"
  UserPoolClientId:
    Description: "UserPoolClientId"
    Value: !Ref UserPoolClient
  UserPoolArn:
    Description: "UserPoolArn"
    Value: !GetAtt UserPool.Arn
    Export: 
      Name: !FindInMap [DomainName, !Ref Environment, name]

